# Generated by Django 4.2.9 on 2024-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='-', max_length=200, null='true', verbose_name='CSS клас'),
            preserve_default='true',
        ),
    ]
